image: node:10.13.0

cache:
  paths:
    - node_modules/

stages:
  - test

Test:
  stage: test
  tags:
    - node
  before_script:
    - npm install
  script:
    # Runs the tests.
    - npm run test
